a = 1
b = 2
c = 3
d = 4
e = 5
f = 6
g = 7
h = 8
j = 9
k = 10
for i in range(1,11):
    print(i, '*',a,'=',a*i)
    print(i, '*',b,'=',b*i)
    print(i, '*',c,'=',c*i)
    print(i, '*',d,'=',d*i)
    print(i, '*',e,'=',e*i)
    print(i, '*',f,'=',f*i)
    print(i, '*',g,'=',g*i)
    print(i, '*',h,'=',h*i)
    print(i, '*',j,'=',j*i)
    print(i, '*',k,'=',k*i)